### ISSUE TITLE
Can you add more mods?

### ISSUE THREAD

**Issue by mannaggacardarell** [MatuxGG/ModManager#1]
If you want i have a list of modded version. I don't know if u can add them or not

- CHEEPYT (Battle Royale - Quantum Tunneling - Color Swap - Confusion - Anonymous - Teleportation - Jester - Infinite Kill Distance - Impostor Invisibility) https://cheep-yt.com/plugins.php?cat=aumods
- CustomRoles: 3 roles in the same game - "The Torch", "The Mayor", and "The Sweeper" https://github.com/tomozbot/AmongUsCustomRoles
- AllOfUs  (Medical - BattleRoyal - Captain - Body Dragging, etc) avaible on their discord: https://cdn.discordapp.com/attachments/798324574752079923/806276174975336468/Launchpad.zip
- Invisibility Mod: https://github.com/gabriel-nsiqueira/invisibility-mod
- SmolMode: https://github.com/XtraCube/SmolMod
- TryHard: https://github.com/Herysia/AmongUsTryhard

Can you add the possibility to launch among us from cmd too? 
And i don't understand if mod are loaded or not because no messagge on top left. I don't know if it's rilevant but i have steam path on another hdd and not on c.
In future if u can add possibility to switch server will be great too

**Comment by MatuxGG** [comment]
Sure !

This version is temporary. Currently, I'm more focused on providing a better UI with an auto install/update system. Once it will be release, you will never have to move ModManager to Among Us folder or get a new version of this software each time a new release is posted :)

Anyways, hanks for sending me these linls. I'll add them as soon as possible !

**Comment by MatuxGG** [comment]
Hi again !

There is a new version of the app that doesn't need that much to work in release section :)
Now, you can choose your Among Us folder and launch the game directly from the app.

I added CustomRoles, SmolMode and TryHard to mods available. I need a few more work to add the others.
Right now, every mod is included in Mod Manager during install. I'm currently working on a feature that download from my website mods you want to use to allow a faster installation (and for me, the ability to add mods more easily, whatever version of Mod Manager you're using).

Enjoy !
