### ISSUE TITLE
Mod Manager won't open

### ISSUE THREAD

**Issue by leeman626** [MatuxGG/ModManager#10]
I have downloaded and extracted the zip for 3.0.0.4 and ran it from there and it wont open... I then downloaded the 3.0.0.4 exe and installed it that way with the same result... any suggestions?

**Comment by MatuxGG** [comment]
matux.fr host provider is currently facing a major issue and Mod Manager rely on it to get mods/textures/dependencies.
For that reason, Mod Manager doesn't work for now but the host provider is on the case.
It will be up again as soon as possible !

See the official discord to get updated ;)

**Comment by MatuxGG** [comment]
Mod Manager should work again now :) There is a new version btw. Enjoy !
