### ISSUE TITLE
Modmanger gui handles some keypress events it doesn't need.

### ISSUE THREAD

**Issue by ThaSiouL** [MatuxGG/ModManager#11]
An example. I have Mouse Button 4 bound to push-to-talk. When i press it while having the mod manager as my active window it handles the keypress event but doesn't do anything.

**Comment by MatuxGG** [comment]
Hello,

That's strange because Mod Manager doesn't interract with keys in any way 😮
I'll investigate about it tho. What is exactly button 4 ?

Anyway, thanks for the report !

**Comment by ThaSiouL** [comment]
It is the back button. On the mouse. If you have like a webview gui it could intercept it. But normal browsers don't consume the event.

**Comment by MatuxGG** [comment]
I will see how I can fix it in new patches then

**Comment by MatuxGG** [comment]
It's been a while but I think I found a way to solve this. Next update will rework many things in Mod Manager and that should make the job

**Comment by MatuxGG** [comment]
I published a new version.
Tell me if the problem is still there for you !
