### ISSUE TITLE
3.0.0.6 can't install "The Other Roles" and "extra Roles"

### ISSUE THREAD

**Issue by ThaSiouL** [MatuxGG/ModManager#13]
I just updated from 3.0.0.5 to 3.0.0.6. since all mods were forgotten i reinstalled them. I tried the other roles as well as extra roles and both were not correctly installed. the server browser on the other hand worked as well as better polus.

**Comment by ThaSiouL** [comment]
PS: both worked on 3.0.0.5

**Comment by MatuxGG** [comment]
It has been hotfix with version 3.0.0.7.

Thanks for the report !
