### ISSUE TITLE
Can't Play Online

### ISSUE THREAD

**Issue by Cosmic-Jester** [MatuxGG/ModManager#14]
Just wanna start off with saying this is a really well put together manager and is easy to use and install mods. However, my friends and I have been trying to play together but none of us can join lobbies with each other. Only the host is allowed in the room and anyone who tries to join shows up as green with ??? for names and are frozen right before joining lobby so they can't even move in game either. We've tried everything and couldn't figure it out.

**Comment by MatuxGG** [comment]
Hello,

I suppose you're trying to play on The Other Roles ? If so, there is an issue right now in the install process for this mod and I'm doing my best to solve this issue asap.

I recommend you to use Town of Us that almost provides the same roles during this time.

Sorry for the inconvenience and thanks for the report :)

Best regards,

**Comment by MatuxGG** [comment]
A new version is out and fixes the problem !

Enjoy :)
