### ISSUE TITLE
Why not copy the directory?

### ISSUE THREAD

**Issue by Ezy04** [MatuxGG/ModManager#18]
Why is it not just copying the Among Us directory and placing the mod inside there? The way it is right now I have to uninstall the mod anytime i wanna switch back to normal among us.

**Comment by MatuxGG** [comment]
Steam often reloads the game on start. Therefore, you can only mod the Among Us directory Steam uses. If you use a side directory to easily switch, launching Among Us from this directory may result in launching the other one.

**Comment by Ezy04** [comment]
Well I have 4 different directories for 4 different mods and they are all opening correctly, aswell as the unmodded version

**Comment by MatuxGG** [comment]
Right, but you're only speaking about yourself here.
I replied to almost 50 support tickets on Mod Manager server and I think 20 of them were related to modding a copy of the original folder.
