### ISSUE TITLE
Crash on launch with no output

### ISSUE THREAD

**Issue by Christian7573** [MatuxGG/ModManager#19]
A friend of mine was using mod manager, and installed a mod that she notes "it said it could corrupt my computer." (I have no idea what actual message she was referring to) Regardless of that, ModManager now crashes on launch with no window, output, or error message. The Administrator prompt opens, she allows admin access, and the application exits.

Tried:
- Reinstalling ModManager
- Reinstalling Among Us
- Reinstalling Among Us but also deleting the AmongUs data folder in Steam
- We were going to delete the ModManager data folder, but there is no ModManager folder in %appdata% (neither Local nor Roaming)
- Running ModManager from PowerShell. The PowerShell did not have admin privileges, but we still approved the admin prompt. The executable exited immediately with no output. Regrettably I did not check the exit code. (Is that even a thing on Windows?)

Any suggestions or pointers to continue debugging?

**Comment by MatuxGG** [comment]
I think version 3.0.0.9 did this for many people. The release 3.0.0.10 should solve your issue. Tell me if it does ;)

**Comment by jacobmix** [comment]
3.0.0.10 not working for me. When i start it, it almost immediately gives the stopped working popup.
Don't actually get to see it run at all, and it creates no logs or anything as far as i can tell.
It does get to make an empty "textures.json" file. Tho it deletes it when i hit "Close the program"
But if i go into Event Viewer i do get this: 
.NET Runtime:
```
Application: ModManager.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Net.WebException
   at System.Net.WebClient.DownloadFile(System.Uri, System.String)
   at System.Net.WebClient.DownloadFile(System.String, System.String)
   at ModManager.TextureList.load()
   at ModManager.ModManager..ctor()
   at ModManager.Program.Main()
```
Application Error:
```
Faulting application name: ModManager.exe, version: 3.0.0.10, time stamp: 0x9efd8611
Faulting module name: KERNELBASE.dll, version: 6.1.7601.24545, time stamp: 0x5e0eb7f5
Exception code: 0xe0434352
Fault offset: 0x0000c5af
Faulting process id: 0x315c
Faulting application start time: 0x01d72053d675f05e
Faulting application path: C:\Program Files (x86)\ModManager3\ModManager.exe
Faulting module path: C:\Windows\syswow64\KERNELBASE.dll
Report Id: 14a614b4-8c47-11eb-98bf-bc5ff4f87f25
```
Hope this helps some.

**Comment by MatuxGG** [comment]
I think you've got some internet issues because that's what webclient error means.

 Actually, the remote textures.json file is reachable, even if textures are disabled. Your problem is different from that issue.

**Comment by Christian7573** [comment]
Updated and resolved! Thanks!
