### ISSUE TITLE
Update available but saying no internet connection

### ISSUE THREAD

**Issue by mlggaimerYT** [MatuxGG/ModManager#21]
![Mod Manager server unavailable 26 03 2021 08_27_46](https://user-images.githubusercontent.com/81010144/112597244-2ae06480-8e0d-11eb-8f83-e3461e7fcafc.png)

**Comment by MatuxGG** [comment]
If you were on version 3.0.0.9 or less, there is an issue solved in next versions that broke the update system.
In this scenario, please make an install from the latest version available on github
