### ISSUE TITLE
Game starts twice and then without the mods

### ISSUE THREAD

**Issue by XoetziX** [MatuxGG/ModManager#27]
Hey, 

when I try to start the game via your ModManager it first starts, I see the Innersloth logo but then the screen gets dark for a very short moment and the game starts again. This time it reaches the main menu, but the mods are not active. 
When it starts the seconds time I see Steam doing something and I also saw your hint in your FAQs regarding Steam often relaunching the game, however I still do not know how I can get rid of this problem. 
I did a copy of a clean installed Among Us, but do not see what this copy should do if I still shall apply the mod to the Steam directory. 

Would be grateful for help!

**Comment by MatuxGG** [comment]
Hey !

First, thanks for reading FAQ ^^

When you didn't select any mod, Steam is relaunched during "unmodding" process. That's normal.

However, if you checked mods, that's not normal.

If it's the case, please, upload you log file here :
- Press Windows + R
- Enter "%APPDATA%/ModManager"
- Select log.txt

**Comment by XoetziX** [comment]
> First, thanks for reading FAQ ^^

I did my very best :-D
 
> When you didn't select any mod, Steam is relaunched during "unmodding" process. That's normal.

I have simply chosen the first mod "The other" for test purposes. 

> However, if you checked mods, that's not normal.
> 
> If it's the case, please, upload you log file here :
> 
[log.txt](https://github.com/MatuxGG/ModManager/files/6489528/log.txt)

>     * Press Windows + R
> 
>     * Enter "%APPDATA%/ModManager"
> 
>     * Select log.txt

here you go and thanks for your help!

**Comment by MatuxGG** [comment]
Apparently, Mod Manager is not able to interract with the Among Us folder.
It happens sometimes but I don't know why.

Uninstalling/reinstalling Among Us from Steam should solve it.

Before that, I'd recommend pressing "Uninstall all" in Mod Manager to prepare it to Mod the game again after

**Comment by XoetziX** [comment]
I did this already. 
I gave it another chance, did the "uninstall all" first and this time I have chosen another HDD as installation folder in order to avoid any "hidden" rights issues on my master disc.  
Unfortunately this did not change anything. 

Here once again the log file, dont know if it helps again. 
[log.txt](https://github.com/MatuxGG/ModManager/files/6489683/log.txt)

Any other ideas which I can try?

**Comment by MatuxGG** [comment]
From log file, it worked :o

**Comment by XoetziX** [comment]
Okay, that is only partially good I think :-D
The double start occurs when starting via the Mod Manager or directly via the among us.exe. 

No other idea what I can try or look at?

**Comment by MatuxGG** [comment]
Mod Manager have no control on Steam reloading the game and in logs, everything looks great.
Mod is installed correctly now so ...

For further help, please consider joining the discord server.

**Comment by MatuxGG** [comment]
Maybe, you don't have Visual C++ redistributable 2015. You can download it here :
https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by Nubanzi** [comment]
I had similar issues. Steam auto-started as administrator. Try to close steam and start steam again (not as admin). Then try tu start Among Us with mods via mod manager

**Comment by XoetziX** [comment]
Hey Nubanzi, thanks for the tip. 
Somehow it works now, before I could try your approach. Quite curious. 
The only thing I can image is that the restart (instead of going to sleep mode usally) I did today had an effect, whatever exactly this should have been?!
