### ISSUE TITLE
Resolution

### ISSUE THREAD

**Issue by KnightDragon140** [MatuxGG/ModManager#28]
I accidently set the resolution to the maximum and now I can't access the button to change it. How do I reset it?

**Comment by MatuxGG** [comment]
Hello,

I'm aware of this and I'm working on a way to prevent this if the future.
To fix it, do the following :
- Press Windows + R
- Enter %APPDATA%/ModManager
- Remove config4.json

As well, there is another bug if you're using custom servers that can happen sometimes. Until there is a fix, following these steps also solve this issue.

Sorry for the inconvenience.

**Comment by KnightDragon140** [comment]
No problem! I've been using this Mod Manager since I think October last year? I'm not sure but thanks for helping me out dude!

**Comment by MatuxGG** [comment]
Today's update fixed it. It will no longer be possible to run into this issue. However, you need to follow steps I gave you to fix it.

I'm happy that you like Mod Manager :)

Please, confirm me that it made the job for you ;)

**Comment by KnightDragon140** [comment]
Dude I don't know what's different in version 5.0.6 but there is only one resolution, and it fits my laptop perfectly. I just found out that the code system still exists. Don't know why I can't change the resolution, but it's fine for me.

**Comment by MatuxGG** [comment]
That's because Mod Manager only shows resolutions that fits your screen now and there are only 5 for biggest screens currently. You may see more for your screen size in the future ;)
