### ISSUE TITLE
some mods issue

### ISSUE THREAD

**Issue by whitegolum** [MatuxGG/ModManager#3]
I used it for some mods and it worked well but only tomozbot/  Mods doesn't work with any other mod i add , whenever i add tomozbot's mods ( custom mods / mayor / etc ... ) the game start screen goes black

**Comment by whitegolum** [comment]
Do you think it's possible for you to add something in your manager ? that writes a script adding every mod in an array table ,each mod added will go in order and marking that crewmate as taken so that exact crewmate won't have more than 1 mod added to it ?

**Comment by MatuxGG** [comment]
For now, combining mods is just purely random. Some are working together well, other doesn't. But I'm just providing a centralized access to mods. I never developped a mod for now so, it's out of my knowledge area. Sorry. Maybe in the future.

In future patches, many things are mods will come however.
