### ISSUE TITLE
About my previous issue

### ISSUE THREAD

**Issue by KnightDragon140** [MatuxGG/ModManager#30]
I didn't mean it displayed one resolution only.
@MatuxGG 
copy and paste the link below
https://user-images.githubusercontent.com/84480265/120360198-7e23d700-c2d6-11eb-9af5-e99a11394daa.png

**Comment by MatuxGG** [comment]
What's your screen resolution ? :o

**Comment by KnightDragon140** [comment]
How do I figure that out?

**Comment by MatuxGG** [comment]
Go to your desktop, right click and the equivalent on this on for your language :

![image](https://user-images.githubusercontent.com/12508157/120377604-a5ea5d80-c31d-11eb-85fe-21bcd2cfffba.png)

Then, you can see it here :

![image](https://user-images.githubusercontent.com/12508157/120377649-b26eb600-c31d-11eb-8a23-b92aa17463a6.png)

**Comment by KnightDragon140** [comment]
1366 x 768

**Comment by MatuxGG** [comment]
Ok there is absolutely no size for your pc '-' That's why

**Comment by brewwmannsna** [comment]
https://hassium.is-inside.me/ta0KNJav.png

1366x786
 send help

**Comment by KnightDragon140** [comment]
It's working perfectly now I can actually see my code.

**Comment by KnightDragon140** [comment]
With plenty of room to spare.
https://user-images.githubusercontent.com/84480265/120472638-1fad3600-c374-11eb-8e05-1688b3fcc99d.png
