### ISSUE TITLE
New update

### ISSUE THREAD

**Issue by KnightDragon140** [MatuxGG/ModManager#34]
I just downloaded the new update that came out yesterday (June 24th) and now whenever trying to load in to the mod manager it gets stuck on the loading bar. It always stops in the same area.
![why it stuck](https://user-images.githubusercontent.com/84480265/123493125-8e835500-d5e9-11eb-97ad-01925e4e7282.png)

**Comment by kobear91** [comment]
I have the same issue did you figure it out?

**Comment by MatuxGG** [comment]
Hello,

Apparently, this issue was linked to an incorrect update of a mod included in Mod Manager.
A few hours ago, it got fixed so it should work correctly now.
Does it work for you ?

Sorry for the inconvenience
