### ISSUE TITLE
Remove Launchpad 

### ISSUE THREAD

**Issue by angxlwtf** [MatuxGG/ModManager#4]
Launchpad is a direct download only, we kindly request that you remove Launchpad from your mod pack. It can also not be used with other mods, so it is pretty much useless to add it to a mod-manager.

Regards,
angxl (All Of Us founder)

**Comment by MatuxGG** [comment]
Sure ! I'll remove it this week end.

**Comment by angxlwtf** [comment]
Thank you!

**Comment by MatuxGG** [comment]
Anyone that update mods or install Mod Manager will no longer be able to use Launchpad now.

**Comment by angxlwtf** [comment]
Thank you so much for cooperating.
