### ISSUE TITLE
Blank screen after start

### ISSUE THREAD

**Issue by XoetziX** [MatuxGG/ModManager#42]
Hello, 

I have just installed the 5.2.2 version, but when I start the Manager I only get a blank screen and nothing happens anymore. see attachment. 
Is there a solution for this problem?

![Screenshot 2022-08-12 184554](https://user-images.githubusercontent.com/82278099/184405380-31215f8a-ac81-4e77-a2e1-ccdbd3fa25c8.jpg)

**Comment by MatuxGG** [comment]
Hi!

Please send your logfile here so I can help you.
- Press Windows + R
- Enter %APPDATA%/ModManager
- Upload logs.txt here

**Comment by MatuxGG** [comment]
Also, if you used chinese language, it may be the reason. An announcement has been made on the discord server.

Please follow these instructions :

![IMG_20220902_104404.jpg](https://user-images.githubusercontent.com/12508157/188101113-8c351973-a3be-4633-90ac-9eda6d96e90d.jpg)

**Comment by XoetziX** [comment]
> Hi!
> 
> Please send your logfile here so I can help you.
> 
>     * Press Windows + R
> 
>     * Enter %APPDATA%/ModManager
> 
>     * Upload logs.txt here


Hello MatuxGG, 

I have just updated to 5.3.1 but I still have the same problem. 
Here are the logs:
[logs.txt](https://github.com/MatuxGG/ModManager/files/9675842/logs.txt)
fyi: I do not have a E: drive at all.

**Comment by MatuxGG** [comment]
Hi, please follow these steps:
- Press Windows + R
- Enter %APPDATA%
- Remove ModManager folder

**Comment by XoetziX** [comment]
This indeed solved the problem, thanks!
