### ISSUE TITLE
mods not installing

### ISSUE THREAD

**Issue by errorlatchkr** [MatuxGG/ModManager#47]
when i select a mod to install the percentage of the download is always stuck at 0%

**Comment by MatuxGG** [comment]
Hi !

Something should be blocking Mod Manager from accessing github/internet then.

Please, join the discord server for further help ;)

**Comment by errorlatchkr** [comment]
I don’t have a phone number for discord and discord is begging for verification

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by MatuxGG** [comment]
Hi, this should be solved !
