### ISSUE TITLE
Add My Mod ExtremeRoles and Extreme Skins

### ISSUE THREAD

**Issue by yukieiji** [MatuxGG/ModManager#51]
ModName : Extreme Roles, Extreme Skins(Extreme Skins is an addon to Extreme Roles for new cosmics)
BepInEx: 6.0.0-be667
GitHub repo: https://github.com/yukieiji/ExtremeRoles
Disord : https://discord.gg/UzJcfBYcyS
Bug reports and suggestion: https://github.com/yukieiji/ExtremeRoles/issues/new/choose (also available in English.)

**Comment by MatuxGG** [comment]
Hi,

It's now available inside Mod Manager. Thanks for the suggestion. For now, it's classified under "Other mods" but as soon as it will grow and keep active, it will be moved to General.

Also, an update is under progress and may come soon. It will add the possibility to combine mods and plugins.

Best regards ;)
