### ISSUE TITLE
it just not open 

### ISSUE THREAD

**Issue by lucasdaweb95** [MatuxGG/ModManager#8]
the process but nothing of the screen

**Comment by MatuxGG** [comment]
Do you mean Mod Manager or Among Us ?

**Comment by lucasdaweb95** [comment]
mod manager

**Comment by MatuxGG** [comment]
A new version is available.

Consider joining the discord server to get help.

Can you give more information please ? Some context ?

**Comment by lucasdaweb95** [comment]
i cant
