### ISSUE TITLE
mod manager won't work with the latest update

### ISSUE THREAD

**Issue by loftyD** [MatuxGG/ModManager#9]
hiya.

I've just gone to enable Vent Digger on the ModManager (along with a few other mods) and they don't seem to work with the latest update of Among Us.  Just wanted to let you know.

**Comment by MatuxGG** [comment]
Hey !

Actually, it's a total mess with last update of Among Us. For now, only Sheriff 2 works from what I've seen so far

**Comment by loftyD** [comment]
Heya

Sorry I thought it may have been an among us thing anyway rather than a mod manager thing anyway :)

Gonna reopen so we can keep this as a reference for when its all back to normal :)

**Comment by MatuxGG** [comment]
Hello,

Many mods are available again right now !
I'll close this issue, don't hesitate to join the discord to be warned when a new mod is updated ! :)

Mod Manager has been updated too.

Enjoy !
